In [2]:
# Page 2: League & Club Structural Evaluations
import pandas as pd
import plotly.express as px

In [3]:
df=pd.read_csv(r'C:\Users\ASUS\FootballPlayerAnalyticsProject\data\FC26_cleaned.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18405 entries, 0 to 18404
Columns: 101 entries, player_id to club_joined_month
dtypes: float64(7), int64(52), str(42)
memory usage: 14.2 MB

In [4]:
# 4. Player Technical Skill Spreads Across Top 5 Leagues
df['league_name'].unique()

<StringArray>
[                       'La Liga',                     'Bundesliga',
                        'Ligue 1',                        'Serie A',
                 'Premier League',                     'Pro League',
            'Major League Soccer',                      'Süper Lig',
        'Hrvatska nogometna liga',     'Liga Profesional de Fútbol',
                  'Primeira Liga',                     'Eredivisie',
                    'Premiership',                     'První liga',
                   'Championship',                         'Liga I',
                        'Ligue 2',                   'Super League',
                    'Eliteserien',                      'No league',
                        'Série A',            'Categoría Primera A',
                      'La Liga 2',                        'Serie B',
               'Primera Division',                  '2. Bundesliga',
                     'K League 1',                   'A-League Men',
                    'Allsvenskan',           'División Profesional',
                      'Superliga',            'Nemzeti Bajnokság I',
               'Primera División',                    'Ekstraklasa',
                         'Liga 1',                     'League One',
                     'League Two',                    '1. Division',
                  'Veikkausliiga', 'División de Fútbol Profesional',
                   'Premyer Liqa',                        '3. Liga',
               'Premier Division']
Length: 43, dtype: str

In [5]:
top5=['Premier League','La Liga','Serie A','Bundesliga','Ligue 1']
df_top5=df[df['league_name'].isin(top5)]
print(df_top5["league_name"].unique())

<StringArray>
['La Liga', 'Bundesliga', 'Ligue 1', 'Serie A', 'Premier League']
Length: 5, dtype: str

In [6]:
fig=px.violin(df_top5,
              x='league_name',
              y='dribbling',
              color='league_name',
              box=True,
              points='outliers',
              template='plotly_white',
              title="Player Technical Skill Spreads Across Top 5 Leagues- Dribbling",
              color_discrete_sequence=px.colors.qualitative.Set2,
              hover_data=['short_name','club_name','age']
              )
fig.update_traces(
    meanline_visible=True,
    hovertemplate=
        '<b>League:</b>%{x}<br>'+
        '<b>Dribbling:</b>{y}<br>'+
        '<b>Player:</b>%{customdata[0]}<br>'+
        "<b>Club:</b> %{customdata[1]}<br>" +
        "<b>Age:</b> %{customdata[2]}<extra></extra>"
)
fig.update_layout(
    title=dict(
        text="Player Technical Skill Spreads Across Top 5 European Leagues-Dribbling",
        x=0.5,
        font=dict(size=24)
    ),

    xaxis_title="League",
    yaxis_title="Dribbling Rating",

    width=1000,
    height=600,

    font=dict(
        family="Arial",
        size=14
    ),

    margin=dict(
        l=70,
        r=40,
        t=80,
        b=70
    ),

    legend_title="League"
)

fig.update_xaxes(
    showgrid=False,
    showline=True,
    linewidth=1,
    linecolor="black",
)

fig.update_yaxes(
    showgrid=True,
    gridcolor="lightgray",
    zeroline=False,
    showline=True,
    linewidth=1,
    linecolor="black",
)


fig.show()

In [7]:
# all skills by grouped bar chart
skill_avg=df_top5.groupby('league_name')[["pace", "shooting", "passing", "dribbling", "defending", "physic"]].mean().reset_index()

In [8]:
skill_avg

,league_name,pace,shooting,passing,dribbling,defending,physic
0,Bundesliga,69.813648,55.598425,60.541995,65.644357,54.757218,66.859580
1,La Liga,70.157787,60.063525,66.883197,70.711066,59.428279,68.176230
2,Ligue 1,70.150812,56.436195,63.004640,68.830626,56.197216,66.517401
3,Premier League,72.022346,60.942272,68.089385,72.646182,61.020484,70.217877
4,Serie A,70.418451,58.762768,63.734761,68.579901,58.794069,68.080725

In [9]:
# conversion from wide format to long format 
skill_avg=skill_avg.melt(
    id_vars="league_name",
    var_name="Technical Skill",
    value_name="Average Rating"
)

In [10]:
skill_avg

       league_name Technical Skill  Average Rating
0       Bundesliga            pace       69.813648
1          La Liga            pace       70.157787
2          Ligue 1            pace       70.150812
3   Premier League            pace       72.022346
4          Serie A            pace       70.418451
5       Bundesliga        shooting       55.598425
6          La Liga        shooting       60.063525
7          Ligue 1        shooting       56.436195
8   Premier League        shooting       60.942272
9          Serie A        shooting       58.762768
10      Bundesliga         passing       60.541995
11         La Liga         passing       66.883197
12         Ligue 1         passing       63.004640
13  Premier League         passing       68.089385
14         Serie A         passing       63.734761
15      Bundesliga       dribbling       65.644357
16         La Liga       dribbling       70.711066
17         Ligue 1       dribbling       68.830626
18  Premier League       dribbling       72.646182
19         Serie A       dribbling       68.579901
20      Bundesliga       defending       54.757218
21         La Liga       defending       59.428279
22         Ligue 1       defending       56.197216
23  Premier League       defending       61.020484
24         Serie A       defending       58.794069
25      Bundesliga          physic       66.859580
26         La Liga          physic       68.176230
27         Ligue 1          physic       66.517401
28  Premier League          physic       70.217877
29         Serie A          physic       68.080725

In [11]:
fig=px.bar(
    skill_avg,
    x='league_name',
    y='Average Rating',
    barmode='group',
    color='Technical Skill',
    template='plotly_white',
    color_discrete_sequence=px.colors.qualitative.Set3,
    title="Average Technical Skills Across Top 5 European Leagues",
    text_auto='.1f'
)
fig.update_traces(
    hovertemplate=
    '<b>%{x}</b><br>'+
    'Skill:%{fullData.name}<br>'+
    'Average Rating:%{y:.1f}<extra></extra>',
    marker=dict(
            line=dict(
                color="black",
                width=1
            )
        ),
    textposition='outside'
)
fig.update_layout(
    title=dict(
        text='Average Technical Skills Across Top 5 European Leagues',
        font=dict(size=24),
        x=0.5
    ),
    width=1000,
    height=600,
    xaxis_title="League",
    yaxis_title="Average Technical Rating",
    legend_title='Technical Skill',
    font=dict(
        size=14,
        family='Arial'
    ),
    margin=dict(
        t=80,
        r=40,
        l=70,
        b=70
    ),
    bargap=0.1,
    bargroupgap=0.03
    )
fig.update_xaxes(showgrid=False, showline=True,
    linewidth=1,
    linecolor="black")

fig.update_yaxes(
    showgrid=True,
    gridcolor="lightgray",
    showline=True,
    linewidth=1,
    linecolor="black",
    range=[0, 100]
)

fig.show()

In [12]:
# 5. Squad Rating Variances within Leagues-It compares how player overall ratings are distributed within each league.
fig=px.box(
    df_top5,
    x='league_name',
    y='overall',
    color='league_name',
    template='plotly_white',
    title='Squad Rating Variances within Top 5 European Leagues',
    points="outliers",
    color_discrete_sequence=px.colors.qualitative.Dark2,
    hover_data=['short_name','club_name','age','overall']
)
fig.update_traces(
    hovertemplate=
    '<b>%{customdata[0]}</b><br>'+ # custom data contains columns you specified in hover_data
    '<b>Club:%{customdata[1]}<br>'+
    "League: %{x}<br>" +
    "Overall Rating: %{y}<br>" +
    "Age: %{customdata[2]}<extra></extra>",
    boxmean=True,
    whiskerwidth=0.8,
    marker=dict(
        size=5,
        opacity=0.8,
        line=dict(
            color='black',
            width=0.5
        )

    )
)
fig.update_layout(
    title=dict(
        text='Squad Rating Variances within Top 5 European Leagues',
        x=0.5,
        font=dict(
            family='Arial',
            size=24,
            color="#2F2F2F"
        )
    ),
    xaxis_title='League',
    yaxis_title='Overall Player Rating',
    font=dict(
        family='Arial',
        size=14
    ),
    height=600,
    width=1000,
    legend_title="League",

    margin=dict(
        l=70,
        r=40,
        t=80,
        b=70
    ),

    hovermode="closest"
)
fig.update_xaxes(
    showgrid=False,
    showline=True,
    linecolor='black',
    linewidth=1
)
fig.update_yaxes(
    showgrid=True,
    gridcolor="lightgray",
    gridwidth=1,
    zeroline=False,
    showline=True,
    linewidth=1,
    linecolor="black",
    range=[40, 100]
)
fig.show()

In [13]:
# 6. League Financial Wage Mix Architecture

# top 5 european leagues
top5 = [
    'La Liga', 'Bundesliga', 'Ligue 1', 'Serie A', 'Premier League'
]
#top 5 leagues filtered
dftop5=df[df['league_name'].isin(top5)]

# sum of wages 
df_sum=dftop5.groupby(['league_name','club_name'])['wage_eur'].sum().reset_index()

# top 10 clubs 
df_sum = (
    df_sum.sort_values("wage_eur", ascending=False)
            .groupby("league_name")
            .head(10)
)

In [14]:

fig = px.treemap(
    df_sum,
    path=["league_name", "club_name"],
    values="wage_eur",
    color="wage_eur",
    color_continuous_scale="Viridis",
    template="plotly_white",
    title="League Financial Wage Mix Architecture",
    hover_data={"wage_eur": ":,"}
)

fig.update_traces(
    textinfo="label+value+percent parent",
    hovertemplate=
    "<b>%{label}</b><br>" +
    "Total Wage: €%{value:,.0f}<br>" +
    "League Share: %{percentParent}<br>" +
    "Overall Share: %{percentRoot}<extra></extra>",

    marker=dict(
        line=dict(
            color="white",
            width=2
        )
    )
)

fig.update_layout(
    title=dict(
        text="League Financial Wage Mix Architecture",
        x=0.5,
        font=dict(
            size=24,
            family="Arial",
            color="#2F2F2F"
        )
    ),

    width=1100,
    height=700,

    margin=dict(
        l=20,
        r=20,
        t=80,
        b=20
    ),

    font=dict(
        family="Arial",
        size=14
    ),

    coloraxis_colorbar=dict(
        title="Total Wage (€)"
    )
)

fig.show()