In [2]:
import pandas as pd
import plotly.express as px

In [3]:
df=pd.read_csv(r'C:\Users\ASUS\FootballPlayerAnalyticsProject\data\FC26_cleaned.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18405 entries, 0 to 18404
Columns: 101 entries, player_id to club_joined_month
dtypes: float64(7), int64(52), str(42)
memory usage: 14.2 MB

In [7]:
# Page 5: Core Attribute & Performance Correlation

# 14. Performance Attribute Interdependency Heatmap
performance=df[[ 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic'] ]
corr=performance.corr()
corr

               pace  shooting   passing  dribbling  defending    physic
pace       1.000000  0.354862  0.294011   0.505129  -0.254569 -0.122258
shooting   0.354862  1.000000  0.667313   0.772998  -0.383667  0.017535
passing    0.294011  0.667313  1.000000   0.862347   0.218030  0.191300
dribbling  0.505129  0.772998  0.862347   1.000000  -0.061176  0.063528
defending -0.254569 -0.383667  0.218030  -0.061176   1.000000  0.524593
physic    -0.122258  0.017535  0.191300   0.063528   0.524593  1.000000

In [15]:
fig=px.imshow(
    corr,
    template='plotly_white',
    color_continuous_scale='Viridis',
    title="Performance Attribute Interdependency Heatmap",
    text_auto='.2f',
    aspect='auto',
    labels=dict(
        color='Correlation'
    )
)
fig.update_traces(
     hovertemplate=
    "<b>%{x}</b> vs <b>%{y}</b><br>" +
    "Correlation: %{z:.2f}<extra></extra>"
)
fig.update_layout(
    title=dict(
        text="Performance Attribute Interdependency Heatmap",
        x=0.5,
        font=dict(
            size=24,
            family="Arial"
        )
    ),
    width=800,
    height=600,
    font=dict(
        family="Arial",
        size=14
    ),
    margin=dict(
        l=70,
        r=40,
        t=80,
        b=70
    )
)

fig.update_xaxes(
    title="Performance Attributes",
    showgrid=False,
    showline=True,
    linecolor="black"
)

fig.update_yaxes(
    title="Performance Attributes",
    showgrid=False,
    showline=True,
    linecolor="black"
)
fig.show()

In [18]:
# 15. Total Wage vs. Total Market Value Progression
data=df.groupby('overall')['value_eur'].mean().reset_index()
data

    overall     value_eur
0        47  1.033333e+05
1        48  1.001429e+05
2        49  9.375000e+04
3        50  1.006075e+05
4        51  1.197794e+05
5        52  1.627969e+05
6        53  1.894335e+05
7        54  2.107812e+05
8        55  2.569692e+05
9        56  2.958179e+05
10       57  3.318989e+05
11       58  3.913645e+05
12       59  4.177720e+05
13       60  4.339244e+05
14       61  5.649294e+05
15       62  6.666685e+05
16       63  7.531908e+05
17       64  8.687430e+05
18       65  1.016674e+06
19       66  1.165927e+06
20       67  1.305801e+06
21       68  1.554058e+06
22       69  1.724362e+06
23       70  1.856938e+06
24       71  2.148288e+06
25       72  2.649570e+06
26       73  3.453316e+06
27       74  4.855792e+06
28       75  6.244740e+06
29       76  8.299474e+06
30       77  1.158755e+07
31       78  1.506527e+07
32       79  1.808529e+07
33       80  2.271339e+07
34       81  2.451512e+07
35       82  2.944382e+07
36       83  3.656140e+07
37       84  4.093111e+07
38       85  4.553333e+07
39       86  6.568750e+07
40       87  7.943182e+07
41       88  8.885714e+07
42       89  1.081923e+08
43       90  1.226000e+08
44       91  1.277500e+08

In [24]:
fig = px.line(
    data,
    x="overall",
    y="value_eur",
    markers=True,
    template="plotly_white",
    color_discrete_sequence=["#3B528B"],
    title="Average Market Value by Overall Rating"
)

fig.update_traces(
    line=dict(width=4),
    marker=dict(
        size=8,
        symbol="circle",
        color="#3B528B",
        line=dict(
            color="black",
            width=1
        )
    ),
    hovertemplate=
    "<b>Overall Rating:</b> %{x}<br>" +
    "<b>Average Market Value:</b> €%{y:,.0f}<extra></extra>"
)
fig.update_layout(
    title=dict(
        text="Average Market Value by Overall Rating",x=0.5,
        font=dict(
            size=24,
            family="Arial"
        )
    ),
    xaxis_title="Overall Rating",
    yaxis_title="Average Market Value (€)",
    width=800,
    height=600,
    font=dict(
        family="Arial",
        size=14),
    margin=dict(
        l=70,
        r=40,
        t=80,
        b=70),
)

fig.update_xaxes(
    showgrid=False,
    showline=True,
    linecolor="black",
)

fig.update_yaxes(
    showgrid=True,
    gridcolor="lightgray",
    showline=True,
    linecolor="black",
    tickprefix="€"
)

fig.show()